/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | "Pacific/Midway"
  | "Pacific/Niue"
  | "Pacific/Honolulu"
  | "Pacific/Rarotonga"
  | "America/Anchorage"
  | "Pacific/Gambier"
  | "America/Los_Angeles"
  | "America/Tijuana"
  | "America/Denver"
  | "America/Phoenix"
  | "America/Chicago"
  | "America/Guatemala"
  | "America/New_York"
  | "America/Bogota"
  | "America/Caracas"
  | "America/Santiago"
  | "America/Buenos_Aires"
  | "America/Sao_Paulo"
  | "Atlantic/South_Georgia"
  | "Atlantic/Azores"
  | "Atlantic/Cape_Verde"
  | "Europe/London"
  | "Europe/Berlin"
  | "Africa/Lagos"
  | "Europe/Athens"
  | "Africa/Cairo"
  | "Europe/Moscow"
  | "Asia/Riyadh"
  | "Asia/Dubai"
  | "Asia/Baku"
  | "Asia/Karachi"
  | "Asia/Tashkent"
  | "Asia/Calcutta"
  | "Asia/Dhaka"
  | "Asia/Almaty"
  | "Asia/Jakarta"
  | "Asia/Bangkok"
  | "Asia/Shanghai"
  | "Asia/Singapore"
  | "Asia/Tokyo"
  | "Asia/Seoul"
  | "Australia/Brisbane"
  | "Australia/Sydney"
  | "Pacific/Guam"
  | "Pacific/Noumea"
  | "Pacific/Auckland"
  | "Pacific/Fiji";

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    AboutPage: AboutPageProps;
    HomePage: HomePageProps;
    NetworkingPage: NetworkingPageProps;
    users: User;
    media: Media;
    attendees: Attendee;
    events: EventProps;
    "marketing-sections": MarketingSection;
    partnersN: PartnersNProps;
    tickets: Ticket;
    gallery7: Gallery7;
    testimonial25: Testimonial25Props;
    statisticsN: StatisticsProps;
    faqLeftRight: FaqLeftRight;
    lecturersN: LecturersNProps;
    agendaN: AgendaNProps;
    contacts: ContactsProps;
    "payload-kv": PayloadKv;
    "payload-locked-documents": PayloadLockedDocument;
    "payload-preferences": PayloadPreference;
    "payload-migrations": PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    AboutPage: AboutPageSelect<false> | AboutPageSelect<true>;
    HomePage: HomePageSelect<false> | HomePageSelect<true>;
    NetworkingPage: NetworkingPageSelect<false> | NetworkingPageSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    attendees: AttendeesSelect<false> | AttendeesSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    "marketing-sections":
      | MarketingSectionsSelect<false>
      | MarketingSectionsSelect<true>;
    partnersN: PartnersNSelect<false> | PartnersNSelect<true>;
    tickets: TicketsSelect<false> | TicketsSelect<true>;
    gallery7: Gallery7Select<false> | Gallery7Select<true>;
    testimonial25: Testimonial25Select<false> | Testimonial25Select<true>;
    statisticsN: StatisticsNSelect<false> | StatisticsNSelect<true>;
    faqLeftRight: FaqLeftRightSelect<false> | FaqLeftRightSelect<true>;
    lecturersN: LecturersNSelect<false> | LecturersNSelect<true>;
    agendaN: AgendaNSelect<false> | AgendaNSelect<true>;
    contacts: ContactsSelect<false> | ContactsSelect<true>;
    "payload-kv": PayloadKvSelect<false> | PayloadKvSelect<true>;
    "payload-locked-documents":
      | PayloadLockedDocumentsSelect<false>
      | PayloadLockedDocumentsSelect<true>;
    "payload-preferences":
      | PayloadPreferencesSelect<false>
      | PayloadPreferencesSelect<true>;
    "payload-migrations":
      | PayloadMigrationsSelect<false>
      | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  globals: {};
  globalsSelect: {};
  locale: null;
  user: User & {
    collection: "users";
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AboutPage".
 */
export interface AboutPageProps {
  id: string;
  statisticsN?: (string | null) | StatisticsProps;
  partners?: (string | null) | PartnersNProps;
  label: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "statisticsN".
 */
export interface StatisticsProps {
  id: string;
  label: string;
  /**
   * Показва се над трите статистики
   */
  title?: string | null;
  statisticsData: {
    /**
     * Трябва поне да е 1:1. 48x48 px ще се рендерира.
     */
    icon?: (string | null) | Media;
    value: number;
    /**
     * Показва се точно до числото, а НЕ на нов ред като описанието.
     */
    suffix?: string | null;
    description: string;
    id?: string | null;
    blockName?: string | null;
    blockType: "statistic";
  }[];
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partnersN".
 */
export interface PartnersNProps {
  id: string;
  /**
   * Така ще се показва раздела, когато го избирате от някоя страница. Да НЕ се трие, и препоръчително да не се пипа.
   */
  label: string;
  subtitle?: string | null;
  images: (string | Media)[];
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HomePage".
 */
export interface HomePageProps {
  id: string;
  subheading?: string | null;
  heroImg?: (string | null) | Media;
  faqLeftRight?: (string | null) | FaqLeftRight;
  gallery7?: (string | null) | Gallery7;
  testimonials25?: (string | null) | Testimonial25Props;
  /**
   * Ако не въведете, ще се показват всички включени актуални събития
   */
  events?: (string | EventProps)[] | null;
  statisticsN?: (string | null) | StatisticsProps;
  partners?: (string | null) | PartnersNProps;
  label: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqLeftRight".
 */
export interface FaqLeftRight {
  id: string;
  title: string;
  label: string;
  helperText: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ("ltr" | "rtl") | null;
      format: "left" | "start" | "center" | "right" | "end" | "justify" | "";
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  QABlock: QABlockProps[];
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "QABlockProps".
 */
export interface QABlockProps {
  question: string;
  answer: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ("ltr" | "rtl") | null;
      format: "left" | "start" | "center" | "right" | "end" | "justify" | "";
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: "qABlock";
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery7".
 */
export interface Gallery7 {
  id: string;
  label: string;
  title: string;
  images: (string | Media)[];
  descr?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ("ltr" | "rtl") | null;
      format: "left" | "start" | "center" | "right" | "end" | "justify" | "";
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  ctaText?: string | null;
  ctaHref?: string | null;
  rotateSpeed?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonial25".
 */
export interface Testimonial25Props {
  id: string;
  label: string;
  title: string;
  helperText?: string | null;
  ctaText?: string | null;
  ctaHref?: string | null;
  /**
   * Добавете отделните карти за препоръки. При нужда копирайте вече съществуващи записи.
   */
  cards: Testimonial25CardProps[];
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "Testimonial25CardProps".
 */
export interface Testimonial25CardProps {
  image: string | Media;
  quote: string;
  author: string;
  role: string;
  company: string;
  id?: string | null;
  blockName?: string | null;
  blockType: "testimonial25CardBlock";
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface EventProps {
  id: string;
  title: string;
  description: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ("ltr" | "rtl") | null;
      format: "left" | "start" | "center" | "right" | "end" | "justify" | "";
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Най-много 1-2 параграфа НЕ повече
   */
  shortDescription?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ("ltr" | "rtl") | null;
      format: "left" | "start" | "center" | "right" | "end" | "justify" | "";
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Stripe Dashboard > Search (top center) > Payment Links > + New; Сложете redirect към сайта. Може с имейл, телефон или комбинация.
   */
  stripeUrl?: string | null;
  type: "networking" | "businessBreakfast" | "conference" | "courses";
  date: string;
  active: "false" | "true";
  /**
   * 2 имена на лектора
   */
  speakerName: string;
  /**
   * поражда Недостиг у хората.
   */
  maxGuests?: string | null;
  /**
   * Препоръчително 1920x1005px (Facebook event banner).
   */
  thumbnail: string | Media;
  /**
   * Важно: Провери дали излиза в Google maps като пръв резултат.
   */
  location?: string | null;
  /**
   * По подразбиране е Gravity Ruin Bar. Може да генерирате url от Google maps > потърси мястото > Бутон "Share".
   */
  locationUrl?: string | null;
  /**
   * Gravity bar по подразбиране
   */
  locationImg?: (string | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "NetworkingPage".
 */
export interface NetworkingPageProps {
  id: string;
  /**
   * Ако не въведете събитие, най-новото ще се покаже.
   */
  event?: (string | null) | EventProps;
  partners?: (string | null) | PartnersNProps;
  label: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "attendees".
 */
export interface Attendee {
  id: string;
  email?: string | null;
  name?: string | null;
  phone?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "marketing-sections".
 */
export interface MarketingSection {
  id: string;
  Partners: {
    partners: PartnersProps[];
  };
  Partners2: {
    partners2: Partners2Props[];
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PartnersProps".
 */
export interface PartnersProps {
  subtitle?: string | null;
  images: (string | Media)[];
  id?: string | null;
  blockName?: string | null;
  blockType: "partners";
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "Partners2Props".
 */
export interface Partners2Props {
  subtitle?: string | null;
  images: (string | Media)[];
  id?: string | null;
  blockName?: string | null;
  blockType: "partners2";
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tickets".
 */
export interface Ticket {
  id: string;
  attendee: string | Attendee;
  /**
   * Трябва да има създадено събитие. /admin > Events > "add new"
   */
  event: string | EventProps;
  source: "stripe" | "manually";
  paymentIntentId?: string | null;
  createdAt: string;
  updatedAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lecturersN".
 */
export interface LecturersNProps {
  id: string;
  title: string;
  label: string;
  subheading?: string | null;
  lecturers: {
    name?: string | null;
    role?: string | null;
    bio?: string | null;
    image: string | Media;
    id?: string | null;
  }[];
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "agendaN".
 */
export interface AgendaNProps {
  id: string;
  title?: string | null;
  label: string;
  items: {
    title: string;
    description?: string | null;
    id?: string | null;
  }[];
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contacts".
 */
export interface ContactsProps {
  id: string;
  /**
   * Показва се над Формуляра за контакти
   */
  title?: string | null;
  subheading?: string | null;
  /**
   * google.com/maps > намери място > "Share" > Embed a map > копирайте само url-a в кавичките. 15 сек  tutorial: https://vento.so/view/9e099913-bb15-4990-af47-5b62dc41b98e?utm_medium=share
   */
  gmaps?: string | null;
  cta: string;
  address?: string | null;
  phones?:
    | {
        phone?: string | null;
        id?: string | null;
      }[]
    | null;
  emails?:
    | {
        email?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Социалки. Важно е да има youtube за SEO.
   */
  socials?:
    | {
        platform:
          | "facebook"
          | "instagram"
          | "twitter"
          | "linkedin"
          | "youtube"
          | "tiktok"
          | "whatsapp"
          | "telegram"
          | "viber"
          | "discord"
          | "snapchat"
          | "pinterest"
          | "reddit"
          | "twitch"
          | "medium"
          | "slack"
          | "skype"
          | "threads"
          | "yelp";
        url: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: "AboutPage";
        value: string | AboutPageProps;
      } | null)
    | ({
        relationTo: "HomePage";
        value: string | HomePageProps;
      } | null)
    | ({
        relationTo: "NetworkingPage";
        value: string | NetworkingPageProps;
      } | null)
    | ({
        relationTo: "users";
        value: string | User;
      } | null)
    | ({
        relationTo: "media";
        value: string | Media;
      } | null)
    | ({
        relationTo: "attendees";
        value: string | Attendee;
      } | null)
    | ({
        relationTo: "events";
        value: string | EventProps;
      } | null)
    | ({
        relationTo: "marketing-sections";
        value: string | MarketingSection;
      } | null)
    | ({
        relationTo: "partnersN";
        value: string | PartnersNProps;
      } | null)
    | ({
        relationTo: "tickets";
        value: string | Ticket;
      } | null)
    | ({
        relationTo: "gallery7";
        value: string | Gallery7;
      } | null)
    | ({
        relationTo: "testimonial25";
        value: string | Testimonial25Props;
      } | null)
    | ({
        relationTo: "statisticsN";
        value: string | StatisticsProps;
      } | null)
    | ({
        relationTo: "faqLeftRight";
        value: string | FaqLeftRight;
      } | null)
    | ({
        relationTo: "lecturersN";
        value: string | LecturersNProps;
      } | null)
    | ({
        relationTo: "agendaN";
        value: string | AgendaNProps;
      } | null)
    | ({
        relationTo: "contacts";
        value: string | ContactsProps;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: "users";
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: "users";
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AboutPage_select".
 */
export interface AboutPageSelect<T extends boolean = true> {
  statisticsN?: T;
  partners?: T;
  label?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HomePage_select".
 */
export interface HomePageSelect<T extends boolean = true> {
  subheading?: T;
  heroImg?: T;
  faqLeftRight?: T;
  gallery7?: T;
  testimonials25?: T;
  events?: T;
  statisticsN?: T;
  partners?: T;
  label?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "NetworkingPage_select".
 */
export interface NetworkingPageSelect<T extends boolean = true> {
  event?: T;
  partners?: T;
  label?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "attendees_select".
 */
export interface AttendeesSelect<T extends boolean = true> {
  email?: T;
  name?: T;
  phone?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  shortDescription?: T;
  stripeUrl?: T;
  type?: T;
  date?: T;
  active?: T;
  speakerName?: T;
  maxGuests?: T;
  thumbnail?: T;
  location?: T;
  locationUrl?: T;
  locationImg?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "marketing-sections_select".
 */
export interface MarketingSectionsSelect<T extends boolean = true> {
  Partners?:
    | T
    | {
        partners?:
          | T
          | {
              partners?: T | PartnersPropsSelect<T>;
            };
      };
  Partners2?:
    | T
    | {
        partners2?:
          | T
          | {
              partners2?: T | Partners2PropsSelect<T>;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PartnersProps_select".
 */
export interface PartnersPropsSelect<T extends boolean = true> {
  subtitle?: T;
  images?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "Partners2Props_select".
 */
export interface Partners2PropsSelect<T extends boolean = true> {
  subtitle?: T;
  images?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partnersN_select".
 */
export interface PartnersNSelect<T extends boolean = true> {
  label?: T;
  subtitle?: T;
  images?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tickets_select".
 */
export interface TicketsSelect<T extends boolean = true> {
  attendee?: T;
  event?: T;
  source?: T;
  paymentIntentId?: T;
  createdAt?: T;
  updatedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery7_select".
 */
export interface Gallery7Select<T extends boolean = true> {
  label?: T;
  title?: T;
  images?: T;
  descr?: T;
  ctaText?: T;
  ctaHref?: T;
  rotateSpeed?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonial25_select".
 */
export interface Testimonial25Select<T extends boolean = true> {
  label?: T;
  title?: T;
  helperText?: T;
  ctaText?: T;
  ctaHref?: T;
  cards?:
    | T
    | {
        testimonial25CardBlock?: T | Testimonial25CardPropsSelect<T>;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "Testimonial25CardProps_select".
 */
export interface Testimonial25CardPropsSelect<T extends boolean = true> {
  image?: T;
  quote?: T;
  author?: T;
  role?: T;
  company?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "statisticsN_select".
 */
export interface StatisticsNSelect<T extends boolean = true> {
  label?: T;
  title?: T;
  statisticsData?:
    | T
    | {
        statistic?:
          | T
          | {
              icon?: T;
              value?: T;
              suffix?: T;
              description?: T;
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqLeftRight_select".
 */
export interface FaqLeftRightSelect<T extends boolean = true> {
  title?: T;
  label?: T;
  helperText?: T;
  QABlock?:
    | T
    | {
        qABlock?: T | QABlockPropsSelect<T>;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "QABlockProps_select".
 */
export interface QABlockPropsSelect<T extends boolean = true> {
  question?: T;
  answer?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lecturersN_select".
 */
export interface LecturersNSelect<T extends boolean = true> {
  title?: T;
  label?: T;
  subheading?: T;
  lecturers?:
    | T
    | {
        name?: T;
        role?: T;
        bio?: T;
        image?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "agendaN_select".
 */
export interface AgendaNSelect<T extends boolean = true> {
  title?: T;
  label?: T;
  items?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contacts_select".
 */
export interface ContactsSelect<T extends boolean = true> {
  title?: T;
  subheading?: T;
  gmaps?: T;
  cta?: T;
  address?: T;
  phones?:
    | T
    | {
        phone?: T;
        id?: T;
      };
  emails?:
    | T
    | {
        email?: T;
        id?: T;
      };
  socials?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}

declare module "payload" {
  export interface GeneratedTypes extends Config {}
}
